export const data = [
    { id: 1, tableNumber: "T001", seatingCapacity: 6, availability: true },
    { id: 2, tableNumber: "T002", seatingCapacity: 4, availability: false },
    { id: 3, tableNumber: "T003", seatingCapacity: 2, availability: true },
    { id: 4, tableNumber: "T004", seatingCapacity: 8, availability: true },
    { id: 5, tableNumber: "T005", seatingCapacity: 4, availability: false },
    { id: 6, tableNumber: "T006", seatingCapacity: 6, availability: true },
    { id: 7, tableNumber: "T007", seatingCapacity: 2, availability: true },
    { id: 8, tableNumber: "T008", seatingCapacity: 4, availability: false },
    { id: 9, tableNumber: "T009", seatingCapacity: 4, availability: true },
    { id: 10, tableNumber: "T010", seatingCapacity: 2, availability: false },
    { id: 11, tableNumber: "T011", seatingCapacity: 8, availability: true },
    { id: 12, tableNumber: "T012", seatingCapacity: 6, availability: false },
    { id: 13, tableNumber: "T013", seatingCapacity: 4, availability: true },
    { id: 14, tableNumber: "T014", seatingCapacity: 6, availability: true },
    { id: 15, tableNumber: "T015", seatingCapacity: 2, availability: true },
    { id: 16, tableNumber: "T016", seatingCapacity: 4, availability: false },
    { id: 17, tableNumber: "T017", seatingCapacity: 8, availability: true },
    { id: 18, tableNumber: "T018", seatingCapacity: 6, availability: true },
    { id: 19, tableNumber: "T019", seatingCapacity: 4, availability: true },
    { id: 20, tableNumber: "T020", seatingCapacity: 2, availability: true },
    { id: 21, tableNumber: "T021", seatingCapacity: 8, availability: false },
    { id: 22, tableNumber: "T022", seatingCapacity: 4, availability: true },
    { id: 23, tableNumber: "T023", seatingCapacity: 6, availability: true },
    { id: 24, tableNumber: "T024", seatingCapacity: 2, availability: false },
    { id: 25, tableNumber: "T025", seatingCapacity: 4, availability: true },
  ];
  