export const data = [
    { id: 1, orderNumber: "RES001", tableNumber: "T007", customer: "Ed Sheeran", status: "ordered", serveTime: "10:00 AM", notes: "This is a note for owner from server", payment: "paid" },
    { id: 2, orderNumber: "RES002", tableNumber: "T012", customer: "Taylor Swift", status: "preparing", serveTime: "12:15 PM", notes: "Requesting extra napkins", payment: "pay" },
    { id: 3, orderNumber: "RES003", tableNumber: "T003", customer: "Adele", status: "prepared", serveTime: "02:30 PM", notes: "Customer decided to leave before order was ready", payment: "paid" },
    { id: 4, orderNumber: "RES004", tableNumber: "T005", customer: "Shawn Mendes", status: "serving", serveTime: "03:00 PM", notes: "Has allergy to peanuts", payment: "paid" },
    { id: 5, orderNumber: "RES005", tableNumber: "T010", customer: "Billie Eilish", status: "served", serveTime: "04:45 PM", notes: "Customer requested vegetarian option", payment: "paid" },
    { id: 6, orderNumber: "RES006", tableNumber: "T008", customer: "Katy Perry", status: "ordered", serveTime: "06:00 PM", notes: "Surprise party for a friend", payment: "pay" },
    { id: 7, orderNumber: "RES007", tableNumber: "T009", customer: "Justin Bieber", status: "preparing", serveTime: "07:15 PM", notes: "Table near the window", payment: "paid" },
    { id: 8, orderNumber: "RES008", tableNumber: "T004", customer: "Rihanna", status: "completed", serveTime: "08:30 PM", notes: "Celebrating birthday", payment: "paid" },
    { id: 9, orderNumber: "RES009", tableNumber: "T002", customer: "Bruno Mars", status: "serving", serveTime: "09:00 PM", notes: "Requested extra spicy food", payment: "paid" },
    { id: 10, orderNumber: "RES010", tableNumber: "T006", customer: "Selena Gomez", status: "canceled", serveTime: "11:00 PM", notes: "Customer had to leave early", payment: "paid" },
    { id: 11, orderNumber: "RES011", tableNumber: "T001", customer: "Chris Hemsworth", status: "prepared", serveTime: "12:00 PM", notes: "Allergic to shellfish", payment: "paid" },
    { id: 12, orderNumber: "RES012", tableNumber: "T014", customer: "Scarlett Johansson", status: "serving", serveTime: "01:30 PM", notes: "VIP guest, special request for quiet corner", payment: "pay" },
    { id: 13, orderNumber: "RES013", tableNumber: "T016", customer: "Robert Downey Jr.", status: "completed", serveTime: "02:00 PM", notes: "Needs gluten-free options", payment: "paid" },
    { id: 14, orderNumber: "RES014", tableNumber: "T011", customer: "Mark Ruffalo", status: "preparing", serveTime: "04:10 PM", notes: "Birthday celebration", payment: "paid" },
    { id: 15, orderNumber: "RES015", tableNumber: "T015", customer: "Chris Evans", status: "ordered", serveTime: "05:30 PM", notes: "Wants extra sauce on the side", payment: "pay" },
    { id: 16, orderNumber: "RES016", tableNumber: "T018", customer: "Tom Holland", status: "serving", serveTime: "07:00 PM", notes: "Has a vegetarian preference", payment: "paid" },
    { id: 17, orderNumber: "RES017", tableNumber: "T017", customer: "Zendaya", status: "prepared", serveTime: "08:45 PM", notes: "Celebrating special event", payment: "paid" },
    { id: 18, orderNumber: "RES018", tableNumber: "T013", customer: "Tom Hiddleston", status: "preparing", serveTime: "09:30 PM", notes: "Enjoying dessert after dinner", payment: "pay" },
    { id: 19, orderNumber: "RES019", tableNumber: "T019", customer: "Natalie Portman", status: "completed", serveTime: "10:30 PM", notes: "Table near the garden", payment: "paid" },
    { id: 20, orderNumber: "RES020", tableNumber: "T020", customer: "Samuel L. Jackson", status: "serving", serveTime: "11:00 PM", notes: "Loves spicy food", payment: "paid" },
    { id: 21, orderNumber: "RES021", tableNumber: "T021", customer: "Eva Mendes", status: "prepared", serveTime: "01:15 PM", notes: "Waiting for a friend", payment: "paid" },
    { id: 22, orderNumber: "RES022", tableNumber: "T022", customer: "Ryan Gosling", status: "preparing", serveTime: "02:45 PM", notes: "Requested wine pairing", payment: "pay" },
    { id: 23, orderNumber: "RES023", tableNumber: "T023", customer: "Emma Stone", status: "serving", serveTime: "03:30 PM", notes: "Loves seafood", payment: "paid" },
    { id: 24, orderNumber: "RES024", tableNumber: "T024", customer: "Meryl Streep", status: "completed", serveTime: "05:00 PM", notes: "Celebrating anniversary", payment: "paid" },
    { id: 25, orderNumber: "RES025", tableNumber: "T025", customer: "Nicole Kidman", status: "ordered", serveTime: "06:15 PM", notes: "Special dietary requests", payment: "pay" },
    { id: 26, orderNumber: "RES026", tableNumber: "T026", customer: "Julia Roberts", status: "preparing", serveTime: "07:20 PM", notes: "Vegetarian meal only", payment: "paid" },
    { id: 27, orderNumber: "RES027", tableNumber: "T027", customer: "Will Smith", status: "prepared", serveTime: "08:00 PM", notes: "Allergic to dairy", payment: "paid" },
    { id: 28, orderNumber: "RES028", tableNumber: "T028", customer: "Denzel Washington", status: "serving", serveTime: "09:10 PM", notes: "Requested medium-rare steak", payment: "paid" },
    { id: 29, orderNumber: "RES029", tableNumber: "T029", customer: "Hugh Jackman", status: "completed", serveTime: "10:30 PM", notes: "Looking for a quiet place to dine", payment: "paid" },
    { id: 30, orderNumber: "RES030", tableNumber: "T030", customer: "Leonardo DiCaprio", status: "ordered", serveTime: "11:45 PM", notes: "Birthday celebration, needs a cake", payment: "pay" },
  ];
  