export const data = [
    { id: "1", categoryName: "Juices", foodCount: 12, public: true },
    { id: "2", categoryName: "Desserts", foodCount: 8, public: true },
    { id: "3", categoryName: "Starters", foodCount: 15, public: false },
    { id: "4", categoryName: "Dosa", foodCount: 7, public: true },
    { id: "5", categoryName: "Burgers", foodCount: 10, public: true },
    { id: "6", categoryName: "Pasta", foodCount: 6, public: true },
    { id: "7", categoryName: "Pizza", foodCount: 5, public: true },
    { id: "8", categoryName: "Ice Cream", foodCount: 4, public: false },
    { id: "9", categoryName: "Sushi", foodCount: 3, public: false },
    { id: "10", categoryName: "Chinese", foodCount: 9, public: true },
    { id: "11", categoryName: "Steaks", foodCount: 6, public: false },
    { id: "12", categoryName: "Sandwiches", foodCount: 11, public: true },
    { id: "13", categoryName: "Tacos", foodCount: 13, public: true },
    { id: "14", categoryName: "Grilled Food", foodCount: 8, public: true },
    { id: "15", categoryName: "Biryani", foodCount: 20, public: false },
    { id: "16", categoryName: "Salads", foodCount: 18, public: true },
    { id: "17", categoryName: "Wraps", foodCount: 7, public: false },
    { id: "18", categoryName: "South Indian Breakfast", foodCount: 14, public: true },
    { id: "19", categoryName: "Vegan Food", foodCount: 5, public: true },
    { id: "20", categoryName: "Smoothies", foodCount: 10, public: true },
    { id: "21", categoryName: "Pancakes", foodCount: 8, public: false },
    { id: "22", categoryName: "Indian Snacks", foodCount: 9, public: true },
    { id: "23", categoryName: "Cakes", foodCount: 12, public: true },
    { id: "24", categoryName: "Momos", foodCount: 11, public: false },
    { id: "25", categoryName: "South Indian Lunch", foodCount: 16, public: true },
  ];
  