export const data = [
  {
    id: "1",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "John Doe",
    cooks: "Chef A",
    price: 19.99,
    offerPrice: 15.99,
    active: true,
    category: ["Breakfast"],
    email: "john.doe@example.com",
  },
  {
    id: "2",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "Jane Smith",
    cooks: "Chef B",
    price: 25.49,
    offerPrice: 20.99,
    active: false,
    category: ["Lunch"],
    email: "jane.smith@example.com",
  },
  {
    id: "3",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "Michael Johnson",
    cooks: "Chef C",
    price: 30.0,
    offerPrice: 25.5,
    active: true,
    category: ["Dinner"],
    email: "michael.johnson@example.com",
  },
  {
    id: "4",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "Emily Davis",
    cooks: "Chef D",
    price: 18.75,
    offerPrice: 16.5,
    active: false,
    category: ["Breakfast", "Lunch", "Dinner", "Brunch", "Milk Shake"],
    email: "emily.davis@example.com",
  },
  {
    id: "5",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "Robert Brown",
    cooks: "Chef E",
    price: 22.0,
    offerPrice: 19.5,
    active: true,
    category: ["Lunch"],
    email: "robert.brown@example.com",
  },
  {
    id: "6",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "Sophia Wilson",
    cooks: "Chef F",
    price: 27.99,
    offerPrice: 24.99,
    active: true,
    category: ["Dinner"],
    email: "sophia.wilson@example.com",
  },
  {
    id: "7",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "James Martinez",
    cooks: "Chef G",
    price: 35.5,
    offerPrice: 32.0,
    active: false,
    category: ["Lunch", "Dinner"],
    email: "james.martinez@example.com",
  },
  {
    id: "8",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "Olivia Taylor",
    cooks: "Chef H",
    price: 20.25,
    offerPrice: 18.0,
    active: true,
    category: ["Breakfast"],
    email: "olivia.taylor@example.com",
  },
  {
    id: "9",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "William Anderson",
    cooks: "Chef I",
    price: 40.99,
    offerPrice: 38.5,
    active: true,
    category: ["Dinner"],
    email: "william.anderson@example.com",
  },
  {
    id: "10",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "Ava Thomas",
    cooks: "Chef J",
    price: 15.99,
    offerPrice: 13.99,
    active: false,
    category: ["Breakfast", "Dinner"],
    email: "ava.thomas@example.com",
  },
  {
    id: "11",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "Alexander White",
    cooks: "Chef K",
    price: 28.75,
    offerPrice: 25.99,
    active: true,
    category: ["Lunch"],
    email: "alexander.white@example.com",
  },
  {
    id: "12",
    image: "https://images.pexels.com/photos/1860208/pexels-photo-1860208.jpeg?cs=srgb&dl=cooked-food-1860208.jpg&fm=jpg",
    name: "Mia Harris",
    cooks: "Chef L",
    price: 17.5,
    offerPrice: 14.99,
    active: false,
    category: ["Breakfast", "Lunch"],
    email: "mia.harris@example.com",
  },
];
