name: Build and Test Workflow

on:
  pull_request:
    branches:
      - main
	  -sprint/2025.1
	  -version/0.1.0

jobs:
  backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Step 3: Build the Spring Boot application
      - name: Build Backend with Gradle
        run: ./gradlew build
        working-directory: jit # Path to your backend directory

  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies and build the React app
      - name: Install and Build Frontend
        run: |
          npm install
          npm run build
        working-directory: ui # Path to your frontend directory
