name: Vulnerability Scan

on:
  push:
    branches:
      - '**'  # Scans all branches on push
  pull_request:
    branches:
      - '**'  # Scans all branches on pull request

jobs:
  frontend_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Frontend Dependencies
        working-directory: ./ui
        run: npm install

      # --- Frontend Static Analysis ---
      - name: Run ESLint
        working-directory: ./ui
        run: npm run lint

      - name: Run Semgrep (Frontend)
        working-directory: ./ui
        run: npx semgrep --config auto --sarif --output semgrep_frontend_report.sarif

      - name: Upload Semgrep Report (Frontend)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./ui/semgrep_frontend_report.sarif

      # --- Frontend Dependency Scanning ---
      - name: Run npm audit
        working-directory: ./ui
        run: npm audit --audit-level high

      # --- Example OWASP Check (Frontend) ---
      - name: Basic XSS Pattern Scan (Example)
        working-directory: ./ui
        run: grep -rniE "(innerHTML|dangerouslySetInnerHTML)" ./src

  backend_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Backend Dependencies (Maven)
        working-directory: ./jit
        run: mvn clean install -DskipTests

      # --- Backend Static Analysis ---
      - name: Run SpotBugs
        working-directory: ./jit
        run: mvn spotbugs:check

      - name: Run Semgrep (Backend)
        working-directory: ./jit
        run: npx semgrep --config auto --sarif --output semgrep_backend_report.sarif

      - name: Upload Semgrep Report (Backend)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./jit/semgrep_backend_report.sarif

      # --- Backend Dependency Scanning ---
      - name: Run OWASP Dependency-Check
        working-directory: ./jit
        run: mvn org.owasp:dependency-check-maven:aggregate

      # --- Example OWASP Check (Backend) ---
      - name: Basic SQL Injection Pattern Scan (Example)
        working-directory: ./jit
        run: grep -rniE "DriverManager.getConnection" ./src/main/java
