name: Vulnerability Scan

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'feature/*'
      - 'sprint/*'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'feature/*'
      - 'sprint/*'

jobs:
  frontend_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        working-directory: ./ui
        run: npm install

      - name: Run ESLint
        working-directory: ./ui
        run: npm run lint

      - name: Run audit-ci for npm
        working-directory: ./ui
        run: npx audit-ci --moderate

      - name: Basic XSS Pattern Scan (Example)
        working-directory: ./ui
        run: |
          if grep -rniE "(innerHTML|dangerouslySetInnerHTML)" ./ui/src; then
            echo "Match found."
            exit 1  # Fail the job if XSS patterns are found
          else
            echo "No match found. Ignoring."
          fi

  backend_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradlew
        working-directory: ./jit
        run: chmod +x ./gradlew

      - name: Install Backend Dependencies (Gradle)
        working-directory: ./jit
        run: ./gradlew assemble

      - name: Run SpotBugs
        working-directory: ./jit
        run: ./gradlew spotbugsMain

      - name: Run OWASP Dependency-Check
        working-directory: ./jit
        run: |
          ./gradlew dependencyCheckAnalyze -Ddependency-check.cache-dir=./cache --info
          ls -R ./jit/build || echo "Build directory not found."

      - name: Run Basic SQL Injection Pattern Scan
        working-directory: ./jit
        run: |
          echo "Checking if application.properties exists..."
          if [ -f ./src/main/resources/application.properties ]; then
            echo "application.properties found. Checking for patterns."
            # Perform the pattern scan
            if grep -rniE "url|username|password" ./src/main/resources/application.properties; then
              echo "Potentially sensitive information found in application.properties."
              exit 1  # Fail the job if sensitive patterns are found
            else
              echo "No sensitive patterns found."
            fi
          else
            echo "application.properties file not found."
          fi
